### ISSUE TITLE
add ng2-bootstrap

### ISSUE THREAD

**Issue by rukkaska** [rogerpadilla/angular2-minimalist-starter#23]
Great work Thanks.
I was manage to add ng2-bootstrap to project with config.ts. But I need to System.config
System.config({
    packages: {
      app: {
        format: 'register',
        defaultExtension: 'js'
      }
    },
    map: {
      moment: 'node_modules/moment/moment.js'
    }
  });
How do you do this?

thanks
rukka

**Comment by SeanSanker** [comment]
I have the same question.

**Comment by rogerpadilla** [comment]
Go to the file "tools/config.ts" and replace the import of "`${NM}/systemjs/dist/system-register-only.src.js`," with "`${NM}/systemjs/dist/system.src.js`, then in the file "client/index.html" you can put the System.config call (before the bootstrap of the app).

Note I'm not calling System.config since default configuration is working fine, thus only including "system-register-only.src.js" instead of "system.src.js" is better for the performance/size.
